// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMF8b53Dqanld_AG4oJZbbwrLjlYimCfk',
    appId: '1:810257036214:android:67a30b5c8095ffcb038717',
    messagingSenderId: '810257036214',
    projectId: 'nexecute-49018',
    databaseURL: 'https://nexecute-49018-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nexecute-49018.appspot.com',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfi6f_WEx7dcATqlZZnV8zraUv2wq5c80',
    appId: '1:810257036214:ios:cd394829942b9d84038717',
    messagingSenderId: '810257036214',
    projectId: 'nexecute-49018',
    databaseURL: 'https://nexecute-49018-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nexecute-49018.appspot.com',
    androidClientId: '810257036214-0o22h8uuikk0ds4fei01p4c9knc39j0t.apps.googleusercontent.com',
    iosClientId: '810257036214-6b9opjknn40trfisfice8i05nurcl070.apps.googleusercontent.com',
    iosBundleId: 'com.jndevworks.nexecute',
  );
}
