// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARm-4urpOQ0trSHKCAkHh2cPTrkIGTC2k',
    appId: '1:810257036214:web:ce1a0060b367740e038717',
    messagingSenderId: '810257036214',
    projectId: 'nexecute-49018',
    authDomain: 'nexecute-49018.firebaseapp.com',
    storageBucket: 'nexecute-49018.appspot.com',
    measurementId: 'G-NQZVPYPJZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMF8b53Dqanld_AG4oJZbbwrLjlYimCfk',
    appId: '1:810257036214:android:a32e78f5b0b30f4a038717',
    messagingSenderId: '810257036214',
    projectId: 'nexecute-49018',
    storageBucket: 'nexecute-49018.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfi6f_WEx7dcATqlZZnV8zraUv2wq5c80',
    appId: '1:810257036214:ios:849dfc4adc97f3ed038717',
    messagingSenderId: '810257036214',
    projectId: 'nexecute-49018',
    storageBucket: 'nexecute-49018.appspot.com',
    iosClientId: '810257036214-5k1im8a6022m5r7tb3ap9tt43e4e0jlb.apps.googleusercontent.com',
    iosBundleId: 'c',
  );
}
